### PR TITLE
Add favicon and stuff

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes GH-471

**Release Note**

```release-note
Add favicon and mobile assets
```

/assign @icco

### CODE REVIEW

**Comment by icco** [comment]
/lgtm

I personally like the all black one the best. The red color doesn't do it for me.

**Comment by sethvargo** [comment]
@icco can you look again - I forgot to, ya know, serve the files

**Review by icco — APPROVED** [review]
/lgtm

**Comment by icco** [comment]
> @icco can you look again - I forgot to, ya know, serve the files

lol. I assumed the static serving was already happening. whoops.

**Pull request merged**
