### PR TITLE
Defensively check deleted_at fields in realm/user join tables for memberships

### PR DESCRIPTION
**Pull request by sethvargo**
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/1564
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/1562

**Release Note**

```release-note
Defensively check `deleted_at fields in realm/user join tables for memberships
```

/assign @whaught

### CODE REVIEW

**Comment by sethvargo** [comment]
I'm gonna do the migration in a separate PR in case we need to cherry-pick this

**Review by whaught — APPROVED** [review]

**Comment by sethvargo** [comment]
Test failure is legit, working on a fix

**Comment by sethvargo** [comment]
`name` became an ambiguous column when joining with realms.

@whaught PTAL

**Comment by whaught** [comment]
/retest

idk why prob seems to be moving slowly. Ambiguous column... makes sense

**Review by whaught — APPROVED** [review]

**Pull request merged**
