### PR TITLE
Add variable monitoring-host-project to alerting module.

### PR DESCRIPTION
**Pull request by yegle**
For multi-project workspaces, a separate empty monitoring host project
is preferred.

Related issue: #460 

**Release Note**

```release-note
action required: if you use the "alerting" Terraform module, you need to change var.project to var.monitoring-host-project. It's recommended to use a separate empty project to host the monitoring workspace. See also https://cloud.google.com/monitoring/workspaces/create#multi-project-ws
```

### CODE REVIEW

**Comment by icco** [comment]
So my concern with this is what happens when monitoring host project is set in different terraform workspaces like we have?

**Comment by yegle** [comment]
Not sure if Terraform can do the work (you can merge one workspace into another workspace, i.e. "migrate" two single project workspace into a multi-project workspaec), but worst thing that could happen, we have to destroy everything in the old single-project workspace, and recreate everything in the multi-project workspace.

**Comment by yegle** [comment]
Oh I see what you mean.

I'm thinking about 3 different projects as variables, `monitoring-host-project`, `key-server-project`, `verification-server-project`. We can then use the `alerting` module outside of key/verification server.

This should be done in a later PR.

**Comment by icco** [comment]
Hmm, the more I think about it, I wonder if we should put this in a separate repo, as this is essentially growing the scope to outside of the verification server.

Thoughts?

**Comment by yegle** [comment]
SGTM

**Comment by icco** [comment]
/close

AI: create new repo called exposure-notifications-monitoring or something

**Comment by yegle** [comment]
@icco Let's maintain the monitoring related Terraform configs here for now?

**Comment by icco** [comment]
> @icco Let's maintain the monitoring related Terraform configs here for now?

Yeah, but I think we should revert this? Seems unnecessary for now?

**Comment by icco** [comment]
We talked about this, merging.

/lgtm
/approve

**Pull request merged**
