### PR TITLE
Upgrade Deps

### PR DESCRIPTION
**Pull request by icco**
## Proposed Changes

* `go get -u -v -d ./...`
* `go mod tidy`

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by sethvargo** [comment]
@icco test failures seem legit. I think its the redigo redis vs the opencenus one

**Comment by icco** [comment]
> @icco test failures seem legit. I think its the redigo redis vs the opencenus one

womp, looks like it. Probably the redigo package updated but opencensus has not. @taddari PTAL, probably need to send a fix to opencensus folks.

**Comment by taddari** [comment]
@icco

	github.com/sethvargo/go-redisstore v0.1.2-opencensus
	github.com/sethvargo/go-redisstore v0.1.2

You need to use opencensus redisstore version instead of the normal one

**Comment by icco** [comment]
> @icco
> 
> ```
> github.com/sethvargo/go-redisstore v0.1.2-opencensus
> github.com/sethvargo/go-redisstore v0.1.2
> ```
> 
> You need to use opencensus redisstore version instead of the normal one

oh, nice. fixed.

**Comment by sethvargo** [comment]
@icco merge conflicts

**Comment by icco** [comment]
> @icco merge conflicts

whee fixed.

**Pull request merged**
