### PR TITLE
switch code already expired response to BadRequest instead of an InternalError

### PR DESCRIPTION
**Pull request by bschlaman**
## Proposed Changes

* Switch code already expired or code already claimed scenario to a 4xx response (was previously 5xx).  Currently returning a 400; I think a 410 could also be an appropriate response.
* Fixing some documentation for this API.
* Added check for this response to the end of "success" subtest for code expiration API.  Code and tests for code expiration via form submission is unchanged.

**Release Note**

```release-note
Switch response code for expiring a code via API which is already expired or claimed
```

### CODE REVIEW

**Comment by bschlaman** [comment]
Note: I chose `api.ErrVerifyCodeInvalid` since it's generic enough to capture both a code being expired or claimed already.  Could also introduce another error type like `api.ErrVerifyCodeNotExpirable` but that seems like overkill

**Comment by sethvargo** [comment]
Hey @bschlaman thanks for the PR. Mike and I spotted something else here (unrelated) that we need to get fixed first. We'll share more in a bit.

That being said, I don't think this is the right approach here. We need to inspect the error (using `errors.Is`) to determine the proper code to return. But hold off on making any changes for now.

**Comment by bschlaman** [comment]
Sounds good, just let me know

**Comment by sethvargo** [comment]
#2264

**Pull request closed without merging**
