### PR TITLE
Process one class of HTTP status constants to named constants

### PR DESCRIPTION
**Pull request by vagababov**
Due to the fact that the formatting is very varying, this PR only
contains one set of such const replacements.
I think I've covered all the statuses in the modified files.

### CODE REVIEW

**Comment by vagababov** [comment]
Seem unrelated.


/test pull-en-server-release-unit
--

**Comment by vagababov** [comment]
The tests constantly fail with
`"message":"failed to get sms signer","request_id":"d5d65387-801b-4fc0-9b5f-4d65e76a114b","realm":2,"error":"failed to get current sms signing key: failed to find signing key: record not found"`

Does not really seem related...

**Comment by sethvargo** [comment]
Could be a problem with CI - we're in the process of switching to GitHub Actions. We'll take a look.

/assign

**Comment by vagababov** [comment]
(sorry for close/reopen set — that's the only way I can trigger rerun 😢 )

**Comment by sethvargo** [comment]
Figured out what's going on. It's gonna take a little bit longer to fix though.

**Comment by sethvargo** [comment]
I think we fixed it. Could you rebase @vagababov

**Comment by vagababov** [comment]
Thanks, done!

**Comment by vagababov** [comment]
ok tests passed!
ready to be stamped!

**Review by mikehelmick — APPROVED** [review]

**Pull request merged**
