### PR TITLE
Add portuguese language translations

### PR DESCRIPTION
**Pull request by arturenault**
## Proposed Changes

* Adding Portuguese language translations.
* Small concern - ISO 639-1 doesn't differentiate between Brazilian and European Portuguese. I did Brazilian Portuguese, but I suspect there would be some differences in these phrases.

**Release Note**

```release-note
Added Portuguese translations.
```

### CODE REVIEW

**Comment by mikehelmick** [comment]
/lgtm

Thanks for the contribution.

**Comment by arturenault** [comment]
Sorry for the noise - realizing I'd like to do some more research as my COVID-related vocabulary is rusty :) will un-draft when I'm more confident.

**Review by sethvargo — APPROVED** [review]
/lgtm

**Pull request merged**
