### PR TITLE
removing unneeded Elevated500 alert

### PR DESCRIPTION
**Pull request by bschlaman**
## Proposed Changes

* remove Elevated500s alert
* remove associated Elevated500.md alerting playbook

**Release Note**

```release-note
removing unneeded alert
```

### CODE REVIEW

**Review by sethvargo — COMMENTED** [review]
Why do we want to remove this? Elevated 500s indicate a problem with the service.

**Comment by bschlaman** [comment]
> Why do we want to remove this? Elevated 500s indicate a problem with the service.

I believe the sentiment is that this is a duplicate of the SLO alerts and CloudSchedulerJobFailed.  @yuriatgoogle @yegle @mariliamelo is that correct?

**Comment by yuriatgoogle** [comment]
Yes, that's correct.


*Yuri Grinshteyn*

Customer Reliability Engineering

thegrinch@google.com

**Pull request merged**
