### PR TITLE
make date required default true for new realms

### PR DESCRIPTION
**Pull request by mikehelmick**
## Proposed Changes

* Make date required the default for new realms to encourage usage of this feature.

**Release Note**

```release-note
"date required" is the default setting on NEW realms only. Existing realms not changed on upgrade.
```

### CODE REVIEW

**Review by sethvargo — APPROVED** [review]
/lgtm

**Review by whaught — APPROVED** [review]
/lgtm

**Comment by mikehelmick** [comment]
the test failure is relevant .. just a moment

**Review by whaught — APPROVED** [review]

**Pull request merged**
