### PR TITLE
Add RealmTokenRemainingCapacityLow alert.

### PR DESCRIPTION
**Pull request by yegle**
This alert is currently set up using a local-exec provisioner, due to
the lack of support to define alert policies using MQL in Terraform.

Part of #810

### CODE REVIEW

**Review by sethvargo — COMMENTED** [review]
This is putting a pretty hard dependency on gcloud and the alpha components. Do you have an idea of when it'll be upstream?

**Comment by yegle** [comment]
I reached out to the team internally and there's currently no timeline on when it will be implemented.

Depending on `gcloud` is less of an issue since you have to run `gcloud` to authenticate before running terraform. Depending on `gcloud alpha` however is indeed a bit of a concern.

**Comment by sethvargo** [comment]
> Depending on gcloud is less of an issue since you have to run gcloud to authenticate before running terraform.

That's not entirely true - you can run Terraform by downloading a service account from the console and setting an envvar.

**Comment by yegle** [comment]
> > Depending on gcloud is less of an issue since you have to run gcloud to authenticate before running terraform.
> 
> That's not entirely true - you can run Terraform by downloading a service account from the console and setting an envvar.

True...

Anyway, would it be possible to accept this as a workaround, until it's officially supported? I imaging most of our alerts will still be defined using Terraform supported features.

**Comment by sethvargo** [comment]
I personally feel that the toil of taking on and maintaining this exceeds that which we get by waiting and just creating them manually for now, but I'm just one opinion. My main concern is that there's a lot of people depending on our Terraform configs, and many of them are not very familiar. This is going to dramatically complicate their installations if they use the alerting module.

**Comment by yegle** [comment]
I see https://github.com/hashicorp/terraform-provider-google/pull/7568 was created yesterday and this would hopefully get landed soon.

I'll close this PR.

**Pull request closed without merging**
