### PR TITLE
Add a test

### PR DESCRIPTION
**Pull request by sethvargo**
**Release Note**

```release-note
NONE
```

/assign @whaught

### CODE REVIEW

**Review by whaught — APPROVED** [review]

**Comment by sethvargo** [comment]
Grumble we seem to have exhausted prow. I'll wait a bit and then retest.

**Review by mikehelmick — APPROVED** [review]

**Comment by chaodaiG** [comment]
> Grumble we seem to have exhausted prow. I'll wait a bit and then retest.

I don't think it's prow. All en prow jobs are set to [request 7CPUs](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/a0a5bbd439f39fc5d5f1ad42508433d11cca6812/prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml#L34), which is already what the node [has](https://pantheon.corp.google.com/kubernetes/nodepool/us-west1-b/oss-prow-build-apollo-server/default-pool?project=oss-prow-build-apollo-server), so each cluster node can only schedule a single pod.

**Comment by sethvargo** [comment]
Hmmm - the error seems to be that the database can't start though, which looks like resource exhaustion

**Comment by chaodaiG** [comment]
> Hmmm - the error seems to be that the database can't start though, which looks like resource exhaustion

[GKE](https://pantheon.corp.google.com/kubernetes/pod/us-west1-b/oss-prow-build-apollo-server/test-pods/01b55c90-1e20-11eb-947a-1291c3289507/details?project=oss-prow-build-apollo-server&pageState=(%22savedViews%22:(%22i%22:%225c13e8a875284b318fd7634aec304e4e%22,%22c%22:%5B%5D,%22n%22:%5B%5D))) failed to tell us how much resource was used for the last failed test

**Comment by chaodaiG** [comment]
Let me see if I can capture it live
/retest

**Comment by chaodaiG** [comment]
It passed...

**Comment by sethvargo** [comment]
Perfect!

**Pull request merged**
