### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by icco**
Updates our dockerfile

 - Move to Alpine - current image has less vulnerabilities than ubuntu. Less of an issue since we aren't running on ubuntu, but #shrugs
 - Add a docker ignore to prevent adding files we don't want in our images. Less of an issue because we are using seperate run container, but a best practice.
 - Split out env layers for easier reading
 - Add goproxy env arg to speed build time by grabbing from secure proxy server.

### CODE REVIEW

**Comment by sethvargo** [comment]
> Move to Alpine - current image has less vulnerabilities than ubuntu. Less of an issue since we aren't running on ubuntu, but #shrugs

We're using multi-stage builds. So while the container is built with golang:1.14, the resulting container uses scratch and copies over the compiled binary.

**Comment by icco** [comment]
> > Move to Alpine - current image has less vulnerabilities than ubuntu. Less of an issue since we aren't running on ubuntu, but #shrugs
> 
> We're using multi-stage builds. So while the container is built with golang:1.14, the resulting container uses scratch and copies over the compiled binary.

Yeah, that's what I meant by "not running on ubuntu". But as there is more default software in the ubuntu image, the list of possible CVEs is greater, and could be triggered by the build process. It is a stretch, but considering how easy it is to switch over, no real downsides.

**Comment by sethvargo** [comment]
Yea, I guess I was just bitten early on? Like go-migrate will totally work and compile on alpine, then fail at runtime inside scratch. I know the same is true for staticcheck.

**Comment by icco** [comment]
Interesting, I haven't run into that. But good to know. Will make sure we're doing runtime checks.

**Pull request merged**
