### PR TITLE
Hide ENX settings once enabled behind advanced panel

### PR DESCRIPTION
**Pull request by sethvargo**
**Release Note**

```release-note
Make it more difficult to accidentally disable ENX
```

/cc @mikehelmick 
/assign @whaught

### CODE REVIEW

**Comment by sethvargo** [comment]
screenshot-20200921-183115@2x

**Comment by sethvargo** [comment]
screenshot-20200921-183118@2x

**Review by whaught — APPROVED** [review]
/lgtm

**Comment by whaught** [comment]
I did find in my browser that if I got to #something and then click in the <nav> dropdown setting, my browser set it to #general but the page didn't actually go there. Weird stuff.

**Comment by sethvargo** [comment]
Yea, I noticed that too and I think it's actually a bug in bootstrap 😦. I couldn't find a good solution.

**Pull request merged**
