### PR TITLE
Remove old metrics in /api/certificate API

### PR DESCRIPTION
**Pull request by yegle**

### CODE REVIEW

**Comment by yegle** [comment]
This PR is ready for review now.

**Review by icco — APPROVED** [review]
/lgtm
/hold

Should we wait till the other metrics have rolled out?

**Comment by yegle** [comment]
If we always `tf apply` after a new binary is deployed, we should be good (new binary deployed -> new metric generated -> `tf apply` to update dashboard). If not (run `tf apply` against an old deployed binary, e.g. run it right now), we will be breaking the dashboard regardless if this PR is merged or not.

So I guess we don't need to wait?

**Comment by yegle** [comment]
We've temporarily pin'ed the alerting module version in our private Terraform config repo. I'll remove the hold label now.

**Pull request merged**
