### PR TITLE
Ensure emails are sanitized

### PR DESCRIPTION
**Pull request by whaught**
## Proposed Changes

* CodeQL doesn't like the email strings since they are user-input. Check they are sanitized.

Note: we are using email content-type: plain in our email header.

### CODE REVIEW

**Comment by mikehelmick** [comment]
Do we need to sanitize the email body or the email address? or both?

**Comment by whaught** [comment]
> Do we need to sanitize the email body or the email address? or both?

I think the email address is the only user-content, but this will make it hard to forget as we change the emailer. We also allow realm admins to override the template which may set the body.

**Review by mikehelmick — APPROVED** [review]

**Pull request merged**
