### PR TITLE
Add system admin message text and maintenance bit

### PR DESCRIPTION
**Pull request by whaught**
Issue https://github.com/google/exposure-notifications-verification-server/issues/1139

## Proposed Changes

* Adding DB fields for a system message and maintenance bit

### CODE REVIEW

**Review by sethvargo — CHANGES_REQUESTED** [review]
This needs to be at a higher level than the realm, since this applies to all realms. I think we need to do an envvar or new table.

**Comment by whaught** [comment]
> This needs to be at a higher level than the realm, since this applies to all realms. I think we need to do an envvar or new table.

I was going to write it to all realms. A new table seems like a lot. This had the advantage of being recyclable for generic messages the system might need to give out in the future (thus the separate bool).

That said if this is just a quick thing for the postgres upgrade, envvar is way easier to write

**Comment by sethvargo** [comment]
The problem with scoping it to the realm is that now a realm needs to be in scope during any operation to check if maintenance mode is active. I think envvar is probably fine for this.

**Comment by whaught** [comment]
> The problem with scoping it to the realm is that now a realm needs to be in scope during any operation to check if maintenance mode is active. I think envvar is probably fine for this.

See https://github.com/google/exposure-notifications-verification-server/pull/1142

**Pull request closed without merging**
