### PR TITLE
Remove code and update defaults for next release

### PR DESCRIPTION
**Pull request by sethvargo**
This removes the TODOs in prep for the next release.

**Release Note**

```release-note
NotifyAnomalies and EnableSMSErrorWebhook are now enabled by default and cannot be disabled.
```

### CODE REVIEW

**Comment by sethvargo** [comment]
Not enabling auto-merge

**Review by mikehelmick — COMMENTED** [review]
Can you hold this for O(week) ?

in case we need to cut a point release

**Comment by sethvargo** [comment]
Yea totally - I don't plan on merging - just keeping it around so we don't forget

**Review by mikehelmick — APPROVED** [review]

**Comment by mikehelmick** [comment]
safe to merge!

**Pull request merged**
