### PR TITLE
Create a clicky test for each admin tab

### PR DESCRIPTION
**Pull request by whaught**
## Proposed Changes

* Creates a basic clicky-test for each admin tab
    * Currently just loads each tab and verifies the body loads without error
    * Next PRs will fill out functionality exercises for each page

**Release Note**

```release-note
Integration test coverage for system-admin UI
```

### CODE REVIEW

**Comment by sethvargo** [comment]
Hmmm... more "connection reset by peer" messages?

**Comment by mikehelmick** [comment]
related to timeouts? didn't you lower the docker test DB to 30 seconds?

**Comment by sethvargo** [comment]
Each database instance can live for up to 30s

**Review by mikehelmick — APPROVED** [review]

**Comment by jeremyfaller** [comment]
Just dropping a note here possibly explaining the `connection reset by peer` errors.

If you look at the code flow in:

`exposure-notifications-verification-server/pkg/database/database.go`

You see that the failure is from BEFORE we set the Timeouts. It's possible that moving the timeouts to BEFORE trying to get gorm to connect will resolve these failed tests.

**Pull request merged**
